# -*- coding: utf-8 -*-
"""Shared machinery for the step-by-step figures under every numerical.

Each chapter script (ch2fig.py .. ch7fig.py) defines its techniques and its
panels, recomputes every number from the problem data, asserts each one is
printed in its ch<N>-num.tex, and hands the figures to render() here.

The pattern is AI's ch2fig.py: one panel per step of the worked solution, a
coloured TECHNIQUE chip on every panel naming the move the step makes, the
decisive step framed as KEY STEP, and a generated index at the top of the
chapter listing every move and where it is used. The figures draw the
SOLUTION, never a source figure ([[exam-notes-style]]: never redraw).

A figure lands in the .tex at a line reading exactly
    % ch<N>fig:slot <name>
and is written between
    % ch<N>fig:<name> (generated by ch<N>fig.py; do not edit)
    ...
    % ch<N>fig:end
so a rerun replaces the old block instead of stacking a second one.
Figures are PNGs so tools/anki_from_notes.py carries them onto the cards.
"""
import os
import re
import subprocess
import sys

import fitz

HERE = os.path.dirname(os.path.abspath(__file__))
FIGS = os.path.join(HERE, "figs")
TECTONIC = os.path.join(HERE, "tectonic.exe")
BS = chr(92)
DPI = 300
MAXPT = 515.0

BASE_COLOURS = r"""
\definecolor{ink}{HTML}{16202A}\definecolor{sub}{HTML}{6B7785}
\definecolor{acc}{HTML}{2563A8}\definecolor{accL}{HTML}{D6E4F5}
\definecolor{mkc}{HTML}{C2410C}\definecolor{mkL}{HTML}{FDEBD9}\colorlet{mkcL}{mkL}
\definecolor{gd}{HTML}{15803D}\definecolor{gdL}{HTML}{DCFCE7}
\definecolor{pin}{HTML}{6D28D9}\definecolor{pinL}{HTML}{EDE9FE}
\definecolor{ruleL}{HTML}{DEE3E8}\definecolor{rowL}{HTML}{F4F7FA}
\definecolor{cA}{HTML}{2563A8}\definecolor{cAL}{HTML}{D6E4F5}
\definecolor{cB}{HTML}{C2410C}\definecolor{cBL}{HTML}{FDEBD9}
\definecolor{cC}{HTML}{15803D}\definecolor{cCL}{HTML}{DCFCE7}
\definecolor{cD}{HTML}{6D28D9}\definecolor{cDL}{HTML}{EDE9FE}
\definecolor{cE}{HTML}{0E7490}\definecolor{cEL}{HTML}{CFFAFE}
"""

# twelve chip colours, assigned to a chapter's techniques in order
CHIP_HEX = ["2563A8", "6D28D9", "DC2626", "B45309", "BE185D", "0F766E",
            "0369A1", "4D7C0F", "7C2D12", "475569", "0E7490", "15803D",
            "9333EA", "A16207", "1E40AF", "9F1239", "065F46", "92400E",
            "5B21B6", "155E75", "B91C1C", "3F6212", "86198F", "57534E"]

STYLES = r"""
\tikzset{
  chip/.style={rounded corners=1.5pt, text=white, font=\tiny\bfseries,
               inner xsep=2pt, inner ysep=1.2pt, anchor=north west},
  frame/.style={draw=ruleL, rounded corners=2pt, line width=0.4pt},
  keyf/.style={draw=mkc, rounded corners=2pt, line width=1.1pt},
  keytag/.style={font=\tiny\bfseries, text=white, fill=mkc, rounded corners=1pt,
                 inner sep=1.2pt, anchor=south east},
  ttl/.style={font=\scriptsize\bfseries, text=acc, anchor=north west, inner sep=0pt},
  eqn/.style={font=\tiny, text=ink, align=flush left, anchor=north west, inner sep=0pt},
  note/.style={font=\tiny, text=sub, align=flush left, anchor=north west, inner sep=0pt},
  cell/.style={minimum width=9mm, minimum height=5mm, inner sep=0pt, font=\scriptsize,
               draw=ruleL, fill=white, text=ink},
  hot/.style={cell, draw=mkc, fill=mkL, line width=0.7pt, font=\scriptsize\bfseries},
  hdr/.style={font=\tiny\bfseries, text=sub, inner sep=1pt},
  inode/.style={draw=acc, fill=accL, rounded corners=2pt, line width=0.7pt,
                align=center, inner sep=2.5pt, text width=3.3cm, font=\tiny},
  leafA/.style={draw=cA, fill=cAL, rounded corners=6pt, line width=0.7pt,
                align=center, inner sep=2.5pt, text width=2.1cm, font=\tiny},
  leafB/.style={draw=cB, fill=cBL, rounded corners=6pt, line width=0.7pt,
                align=center, inner sep=2.5pt, text width=2.1cm, font=\tiny},
  leafC/.style={draw=cC, fill=cCL, rounded corners=6pt, line width=0.7pt,
                align=center, inner sep=2.5pt, text width=2.1cm, font=\tiny},
  leafD/.style={draw=cD, fill=cDL, rounded corners=6pt, line width=0.7pt,
                align=center, inner sep=2.5pt, text width=2.1cm, font=\tiny},
  edge/.style={draw=sub, line width=0.6pt, -{Stealth[length=2.2mm]}},
  elab/.style={fill=white, inner sep=1.2pt, font=\scriptsize\bfseries, text=ink},
  dot/.style={circle, inner sep=0pt, minimum size=2.2mm, draw=white, line width=0.4pt},
}
"""


class Techs(object):
    """A chapter's moves: key -> (chip label, meaning), in index order."""

    def __init__(self, items):
        self.order = [k for k, _, _ in items]
        self.label = {k: lab for k, lab, _ in items}
        self.what = {k: w for k, _, w in items}
        self.col = {k: "t%s" % re.sub(r"[^A-Za-z]", "", k) for k, _, _ in items}
        self.hex = {k: CHIP_HEX[i % len(CHIP_HEX)] for i, k in enumerate(self.order)}
        self.used = {k: [] for k in self.order}   # (figure short name, step, key?)

    def colours(self):
        return "".join(r"\definecolor{%s}{HTML}{%s}" % (self.col[k], self.hex[k])
                       for k in self.order)

    def chip(self, k, where, name):
        return r"\node[chip, fill=%s] (%s) at %s {%s};" % (self.col[k], name, where,
                                                            self.label[k])

    def index(self, fullwidth_cm=16.6):
        if len(self.order) > 20:
            return self.index2(fullwidth_cm)
        rows = []
        for k in self.order:
            where = []
            seen = {}
            for fig, step, key in self.used[k]:
                seen.setdefault(fig, []).append(
                    (r"\textbf{\color{mkc}%d}" % step) if key else str(step))
            for fig, steps in seen.items():
                where.append("%s %s" % (fig, ",".join(steps)))
            rows.append(r"\tikz[baseline=(c.base)]\node[chip, fill=%s, anchor=base] (c) {%s};"
                        r" & %s & \leavevmode{\color{sub}%s} \\"
                        % (self.col[k], self.label[k], self.what[k],
                           "; ".join(where) or "--"))
        w2 = 0.46 * fullwidth_cm
        w3 = fullwidth_cm - w2 - 3.0
        return (r"\begin{panelbox}\footnotesize\renewcommand{\arraystretch}{1.35}"
                r"\begin{tabular}{@{}l>{\raggedright\arraybackslash}p{%.1fcm}"
                r">{\raggedright\arraybackslash}p{%.1fcm}@{}}"
                r"\textbf{Move} & \textbf{What it says} & \textbf{Where it is used"
                r" (problem, step; {\color{mkc}orange} = the key step)} \\ \hline"
                % (w2, w3) + "\n" + "\n".join(rows) + r"\end{tabular}\end{panelbox}")


    def where(self, k):
        seen = {}
        for fig, step, key in self.used[k]:
            seen.setdefault(fig, []).append((r"\textbf{\color{mkc}%d}" % step) if key else str(step))
        return "; ".join("%s %s" % (f, ",".join(s)) for f, s in seen.items()) or "--"

    def index2(self, fullwidth_cm):
        """Two side-by-side tables: a long index would otherwise fill a page."""
        half = (fullwidth_cm - 0.6) / 2
        colw = half - 2.55
        body = []
        for k in self.order:
            body.append(r"\tikz[baseline=(c.base)]\node[chip, fill=%s, anchor=base] (c) {%s};"
                        r" & %s\newline{\color{sub}\scriptsize %s} \\"
                        % (self.col[k], self.label[k], self.what[k], self.where(k)))
        n = (len(body) + 1) // 2
        head = (r"\begin{tabular}[t]{@{}l>{\raggedright\arraybackslash}p{%.2fcm}@{}}"
                r"\textbf{Move} & \textbf{What it says} {\color{sub}\scriptsize(where: problem, step;"
                r" {\color{mkc}orange} = key step)} \\ \hline" % colw)
        tabs = [head + "\n" + "\n".join(part) + r"\end{tabular}" for part in (body[:n], body[n:])]
        return (r"\begin{panelbox}\scriptsize\renewcommand{\arraystretch}{1.2}"
                + tabs[0] + r"\hspace{0.6cm}" + tabs[1] + r"\end{panelbox}")


def preamble(techs):
    return (r"\documentclass[border=4pt, multi=panelbox]{standalone}" "\n"
            r"\usepackage[T1]{fontenc}\usepackage[default]{lato}" "\n"
            r"\usepackage{amsmath, amssymb, xcolor, tikz, array}" "\n"
            r"\usetikzlibrary{arrows.meta, positioning, calc, shapes.misc}" "\n"
            + BASE_COLOURS + techs.colours() + "\n"
            + r"\newenvironment{panelbox}{}{}"
            + r"\newcommand{\mk}[1]{\textcolor{mkc}{\bfseries #1}}" "\n"
            + STYLES + r"\begin{document}" "\n")


# ---------------------------------------------------------------- panels
def panel(techs, fig, step, title, tech, body, w, h, key=False, eq=None):
    """One framed step panel of width w, height h (cm).

    body: tikz lines drawn in the box (0,0)-(w,h) BELOW the title+chip strip,
    i.e. the drawing area is (0,0) .. (w, h-0.62). eq: optional one-line
    argument set under the drawing (already in the h budget).
    """
    for t in tech:
        techs.used[t].append((fig, step, key))
    L = [BS + "begin{tikzpicture}"]
    L.append(r"\path[use as bounding box] (-0.12,-0.12) rectangle (%.2f,%.2f);"
             % (w + 0.12, h + 0.14))
    L.append(r"\node[ttl] at (0,%.2f) {%d.\ %s};" % (h, step, title))
    prev = None
    for i, t in enumerate(tech):
        where = "(0,%.2f)" % (h - 0.32) if prev is None else \
            "([xshift=1pt]%s.north east)" % prev
        L.append(techs.chip(t, where, "k%d" % i))
        prev = "k%d" % i
    L += body
    if eq:
        L.append(r"\node[eqn, text width=%.2fcm] at (0,%.2f) {%s};" % (w, eq[1], eq[0]))
    L.append(r"\draw[%s] (-0.08,-0.08) rectangle (%.2f,%.2f);"
             % ("keyf" if key else "frame", w + 0.08, h + 0.1))
    if key:
        L.append(r"\node[keytag] at (%.2f,-0.08) {KEY STEP};" % (w + 0.08))
    L.append(BS + "end{tikzpicture}")
    return "\n".join(L)


def grid(panels, per_row, legend=None):
    rows = [panels[i:i + per_row] for i in range(0, len(panels), per_row)]
    L = [r"\begin{panelbox}",
         r"\setlength{\tabcolsep}{1.2mm}\renewcommand{\arraystretch}{1.3}",
         r"\begin{tabular}{@{}" + "c" * per_row + r"@{}}"]
    for r in rows:
        cells = list(r) + [""] * (per_row - len(r))
        L.append(" &\n".join(cells) + r" \\")
    L.append(r"\end{tabular}")
    if legend:
        L.insert(1, r"\begin{tabular}{@{}c@{}}")
        L.append(r"\\[1pt]" + legend)
        L.append(r"\end{tabular}")
    L.append(r"\end{panelbox}")
    return "\n".join(L)


def rows(*rowlists):
    """Several rows of panels, each row its own width, in ONE figure."""
    L = [r"\begin{panelbox}", r"\setlength{\tabcolsep}{1.2mm}\renewcommand{\arraystretch}{1.3}",
         r"\begin{tabular}{@{}c@{}}"]
    for r in rowlists:
        L.append(r"\begin{tabular}{@{}" + "c" * len(r) + r"@{}}" + " &\n".join(r)
                 + r"\end{tabular}\\")
    L += [r"\end{tabular}", r"\end{panelbox}"]
    return "\n".join(L)


def single(tikz):
    return r"\begin{panelbox}" + "\n" + tikz + "\n" + r"\end{panelbox}"


# ---------------------------------------------------------------- replay
def flat(s):
    return re.sub(r"\s+", " ", s)


def section(tex, start, end=None):
    """The slice of the .tex between two markers (a problem's own text)."""
    i = tex.find(start)
    if i < 0:
        sys.exit("marker not found in .tex: %r" % start)
    j = tex.find(end, i + len(start)) if end else len(tex)
    return tex[i:j if j > 0 else len(tex)]


def need(where, label, *strings):
    """Every string must be printed in `where` (whitespace-insensitive)."""
    f = flat(where)
    for s in strings:
        if flat(s) not in f:
            sys.exit("%s: %r is not printed where the figure says it is" % (label, s))


def f3(x):
    return "%.3f" % x


# ---------------------------------------------------------------- render
def render(figs, tex_path, prefix, captions, scale=None):
    """Compile every figure, save PNGs, write each block at its slot.

    scale: {name: factor} for figures drawn in tiny type (trees) that should
    print larger than their natural size, still capped at the text width.
    """
    scale = scale or {}
    mark = "% " + prefix + ":"
    slot = mark + "slot "
    work = os.path.join(FIGS, "_" + prefix)
    os.makedirs(work, exist_ok=True)
    pre = figs[0][1]
    body = [b for _, b in figs[1:]]
    doc = pre + "\n\n".join(body) + "\n" + BS + "end{document}\n"
    open(os.path.join(work, prefix + ".tex"), "w", encoding="utf-8").write(doc)
    r = subprocess.run([TECTONIC, "-X", "compile", prefix + ".tex"], cwd=work,
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit(r.stdout[-4000:] + r.stderr[-4000:])
    figs = figs[1:]
    pdf = fitz.open(os.path.join(work, prefix + ".pdf"))
    if len(pdf) != len(figs):
        sys.exit("expected %d pages, got %d" % (len(figs), len(pdf)))
    widths, heights = {}, {}
    for (name, _), page in zip(figs, pdf):
        page.get_pixmap(dpi=DPI).save(os.path.join(FIGS, name + ".png"))
        widths[name] = min(page.rect.width * scale.get(name, 1.0), MAXPT)
        heights[name] = page.rect.height * widths[name] / page.rect.width
    if "--figs-only" in sys.argv:
        print("%d figures rendered, .tex untouched" % len(figs))
        return
    src = open(tex_path, encoding="utf-8").read()
    src = re.sub(r"(?m)^" + re.escape(mark) + r"(?!slot )\S+ \(generated.*?^"
                 + re.escape(mark) + r"end\n", "", src, flags=re.S)
    for name, _ in figs:
        anchor = slot + name
        i = src.find(anchor)
        if i < 0:
            sys.exit("no slot for %s in %s" % (name, os.path.basename(tex_path)))
        if src[i - 1:i] != "\n" or not src[i + len(anchor):].startswith("\n"):
            sys.exit("slot for %s is not alone on its line" % name)
        j = src.find("\n", i) + 1
        block = (mark + name + " (generated by %s.py; do not edit)\n" % prefix
                 + BS + "par" + BS + "penalty0" + BS + "vspace{3pt}\n"
                 + BS + "Needspace{%.0fpt}\n" % (heights[name] + 24)
                 + BS + "lead{" + captions[name] + "}\n"
                 + BS + "begin{center}" + BS
                 + "includegraphics[width=%.1fpt]{figs/%s.png}" % (widths[name], name)
                 + BS + "end{center}\n"
                 + mark + "end\n")
        src = src[:j] + block + src[j:]
    open(tex_path, "w", encoding="utf-8").write(src)
    print("%d figures written" % len(figs))
